DROP TABLE IF EXISTS kerbside;

CREATE TABLE kerbside (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  suburb TEXT NOT NULL,
  kerbside_week DATE NOT NULL
);