DROP TABLE IF EXISTS kerbside;
DROP TABLE IF EXISTS datefetches;

CREATE TABLE kerbside (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  suburb TEXT NOT NULL,
  kerbside_week DATE NOT NULL
);

CREATE TABLE datefetches (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)